[package]
name = "conveyors"
version = "0.1.0"
authors = ["Darrell Hamilton <darrell.noice@gmail.com>"]

[dependencies]
clap = "2.19.2"
# hyper = "0.9.13"
iron = "0.4.0"

[[bin]]
name = "conveyors"
path = "src/main.rs"
